App\Entity\Product:
  type: entity
  table: product

  id:
    id:
      type: string

  manyToOne:
    machine:
      targetEntity: Machine
      inversedBy: products

  fields:
    name:
      type: string
      nullable: false
    cost:
      type: float
      presision: 8
      scale: 2
      nullable: false
    stock:
      type: integer
      nullable: false
    createdAt:
      type: datetime
      nullable: false
    updatedAt:
      type: datetime
      nullable: false

  lifecycleCallbacks:
    preUpdate: [markAsUpdated]