App\Entity\HistorySale:
  attributes:
    normalization_context:
      groups: ['history_sale_read']
    filters:
      - app.historySale.search_filter
      - ApiPlatform\Core\Bridge\Doctrine\Orm\Filter\DateFilter
      - ApiPlatform\Core\Bridge\Doctrine\Orm\Filter\OrderFilter
  collectionOperations:
    get:
      method: 'GET'
      security: 'is_granted("HISTORY_SALE_READ")'
      openapi_context:
        summary: Get the collection of sale
        description: End point to get all sales

  itemOperations:
    get:
      method: 'GET'
      security: 'is_granted("HISTORY_SALE_READ", object)'
      openapi_context:
        summary: Get one sale
        description: End point to get one sale