App\Entity\Machine:
  attributes:
  collectionOperations:
    get:
      method: 'GET'
      security: 'is_granted("PRODUCT_READ")'
      normalization_context:
        groups: ['machine_read']
      openapi_context:
        summary: Get the collection of machines
        description: End point to get all machines

  itemOperations:
    get:
      method: 'GET'
      security: 'is_granted("MACHINE_READ", object)'
      normalization_context:
        groups: ['machine_read']
      openapi_context:
        summary: Get machine
        description: End point to get one machine

    patch_wallet:
      method: 'PATCH'
      path: '/machines/insert-wallet/{id}'
      security: 'is_granted("MACHINE_UPDATE_WALLET", object)'
      normalization_context:
        groups: ['machine_read']
      denormalization_context:
        groups: ['machine_patch_insert_wallet']
      openapi_context:
        summary: Return wallet of vending machine
        description: End point to return all wallet of vending machine
        requestBody:
          content:
            application/json:
              schema:
                type: object
                properties:
                  wallet:
                    type: number

    return_wallet:
      method: 'PATCH'
      path: '/machines/return-wallet/{id}'
      security: 'is_granted("MACHINE_PATCH_RETURN_WALLET", object)'
      normalization_context:
        groups: ['machine_read']
      denormalization_context:
        groups: ['machine_patch_return_wallet']
      openapi_context:
        summary: Return wallet of vending machine
        description: End point to return all wallet of vending machine
        requestBody:
          content:
            application/json:
              schema:
                type: object

    patch_cash:
      method: 'PATCH'
      path: '/machines/insert-cash/{id}'
      security: 'is_granted("MACHINE_UPDATE_CASH", object)'
      normalization_context:
        groups: ['machine_read_insert_cash']
      denormalization_context:
        groups: ['machine_patch_insert_cash']
      openapi_context:
        summary: Add cash to vending machine
        description: End point to add money to vending machine
        requestBody:
          content:
            application/json:
              schema:
                type: object
                properties:
                  cash:
                    type: number

    return_cash:
      method: 'PATCH'
      path: '/machines/return-cash/{id}'
      security: 'is_granted("MACHINE_PATCH_RETURN_CASH", object)'
      normalization_context:
        groups: ['machine_read_return_cash']
      denormalization_context:
        groups: ['machine_patch_return_cash']
      openapi_context:
        summary: Return cash of vending machine
        description: End point to return all cash of vending machine
        requestBody:
          content:
            application/json:
              schema:
                type: object

  properties:
    products:
      subresource:
        subresourceClass: 'App\Entity\Product'
        collection: true
        maxDepth: 1