App\Entity\User:
  attributes:
    normalization_context:
      groups: ['user_read']

  collectionOperations:
    get:
      method: 'GET'
      security: 'is_granted("USER_READ")'
      openapi_context:
        summary: Get the collection of users
        description: End point to get all users

  itemOperations:
    get:
      method: 'GET'
      security: 'is_granted("USER_READ", object)'
      openapi_context:
        summary: Get one  user
        description: End point to get one user