imports:
    - { resource: api_platform/filters/product.custom-filter.yaml }
    - { resource: api_platform/filters/historySale.custom-filter.yaml }

services:
    _defaults:
        autowire: true
        autoconfigure: true

        bind:
            $roleValidators: !tagged app.role_validator

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Api\:
        resource: '../src/Api'
        tags: ['controller.service_arguments']

    App\Api\Listener\JsonExceptionResponseTransformerListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: 100 }

    _instanceof:
        App\Api\Listener\PreWriteListener:
            tags:
                - { name: kernel.event_listener, event: kernel.view, method: onKernelView, priority: 33 }

        App\Security\Validator\Role\RoleValidator:
            tags: [ 'app.role_validator' ]

    # API Platform filters
    ApiPlatform\Core\Bridge\Doctrine\Orm\Filter\SearchFilter:
        tags: [ 'api_platform.filter' ]

    ApiPlatform\Core\Bridge\Doctrine\Orm\Filter\DateFilter:
        tags: [ 'api_platform.filter' ]

    ApiPlatform\Core\Bridge\Doctrine\Orm\Filter\OrderFilter:
        tags: [ 'api_platform.filter' ]